version: '3'

services:

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
      - "587"
    volumes:
      - web-static:/static
      - web-media:/media    
    environment:
      DEBUG: 'true'

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/usr/src/app/static
      - web-media:/usr/src/app/media
      - web-label:/usr/src/app/label
    links:
      - web
      - cups

  # a integrated cups-server 
  cups:
    restart: always
    build: ./cups/
    ports:
      - "631:631"


volumes:
  web-static:
  web-media:
